# This file will contain the path's of the required folders

root : artifacts

# data input and output paths
data_paths:
  root_dir : artifacts/data_input
  source_URL: https://drive.google.com/file/d/1Bxj1dVwh6JoEiUdpP0riS5BfrPh-Llbt/view?usp=sharing
  download_folder_path : artifacts/datasets
  local_data_file : artifacts/datasets/winequality-red.csv
  processed_data : artifacts/processed_dataset